language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
notifications:
  email: true
script:
  - npm run coverage
env:
  global:
    - CC_TEST_REPORTER_ID=a3b5fa0b28c8c9714707718b661ddd515bb8f62181d62f3d27e3cc1e8531ad1c
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
