export {ID3v1} from './lib/id3v1/id3v1';
export {ID3v2} from './lib/id3v2/id3v2';
export {MP3} from './lib/mp3/mp3';
export {simplifyTag} from './lib/id3v2/id3v2_simplify';
export * from './lib/common/types';
export * from './lib/id3v2/id3v2_builder';
export * from './lib/id3v2/id3v2__types';
export * from './lib/id3v1/id3v1__types';
export * from './lib/mp3/mp3__types';
