name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - run: npm ci
    - run: npm run build
    - run: npm run test
